# Generated by Django 2.2 on 2019-06-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(choices=[('player', 'Player'), ('captain', 'Captain'), ('v_captain', 'Vice_Captain')], default='Player', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('fy', 'FY'), ('sbs', 'SBS'), ('sps', 'SPS'), ('scs', 'SCS'), ('sms', 'SMS')], default='FY', max_length=10),
        ),
    ]
