# Generated by Django 2.2 on 2019-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190620_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default="static './img/default_member.png'", upload_to='images/'),
        ),
    ]
